# Go for explore more Attributes & methods

*** https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html ***


# Welcome tho numpy

In [103]:
import numpy as np # Including the numpy library

In [104]:
myarr = np.array([[1,3,4,6,7,12]])

In [105]:
myarr[0]

array([ 1,  3,  4,  6,  7, 12])

# Array creation: Convertion from other Python structure

In [106]:
listarray = np.array([  #Create a array
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [107]:
listarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
listarray.dtype #Give the data type of array

dtype('int64')

In [109]:
listarray.shape # Give the array shape

(3, 4)

In [110]:
listarray.size # Give the array size

12

In [111]:
zeros = np.zeros((2,5)) #Create a matrix with the value 0

In [112]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [113]:
rng = np.arange(15) #Create 1D array for a specfic rang

In [114]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [115]:
lspace = np.linspace(1,5,4) # Create space between 1st & last element

In [116]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [117]:
emp = np.empty((4,6)) 

In [118]:
emp

array([[3.18079702e-315, 0.00000000e+000, 5.82133045e-317,
        5.82465847e-317, 5.82195099e-317, 5.82425927e-317],
       [5.82175337e-317, 5.82406560e-317, 5.82124745e-317,
        5.82274940e-317, 5.82259130e-317, 5.82148855e-317],
       [5.82298656e-317, 5.82192728e-317, 5.82167827e-317,
        5.82354386e-317, 5.82351619e-317, 5.82433832e-317],
       [5.82225534e-317, 5.82162294e-317, 5.82414860e-317,
        5.82138578e-317, 5.82095891e-317, 6.88657618e-310]])

In [119]:
emp_like = np.empty_like(lspace)

In [120]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [123]:
ide = np.identity(4) #Create a Identity matrix

In [124]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [125]:
arr = np.arange(99) #Create a 1D arry 0 to 98

In [126]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [129]:
arr = arr.reshape(3,33) #Convert 1D array to 2D array
                        #Focusing on the row and column

In [130]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [131]:
arr.ravel() #Convert 2D array to 1D array
            #Focusing on the row and column

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# NUMPY AXIS

In [132]:
X = [[1,2,3],
     [4,5,6],
     [7,1,0]]

In [133]:
ar = np.array(X)

In [134]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [135]:
ar.sum(axis=0) #It return Sum of all the 0/Y axis value

array([12,  8,  9])

In [136]:
ar.sum(axis=1) #It return Sum of all the 1/X asix value

array([ 6, 15,  8])

# Attribute & Methode

In [148]:
ar.T #attribute without ()
     #Transports a 2d array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [138]:
ar.flat

In [139]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [140]:
ar.ndim #It gives the dimention of array

2

In [141]:
ar.size #It gives the elements number in the array

9

In [142]:
ar.nbytes # It give the bytes size which is consume by array  elements

72

In [144]:
one = np.array([1,3,4,634,2]) 

In [145]:
one.argmax() #Method with ()
             #It gives the largest element index

np.int64(3)

In [146]:
one.argmin() #It gives the smallest element index

np.int64(0)

In [147]:
one.argsort() # Ii give sorted indexs

array([0, 4, 1, 2, 3])

In [149]:
ar.argmin()

np.int64(8)

In [150]:
ar.argmax()

np.int64(6)

In [151]:
ar.argmax(axis=0)

array([2, 1, 1])

In [152]:
ar.argmax(axis=1)

array([2, 2, 0])

In [153]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

# Mathmatical Operation

In [161]:
ar2 = np.array([[1,2,1],         
               [4,0,6],
               [8,1,0]])
                        
                         #ar = [[1,2,3],
                         #      [4,5,6],
                         #      [7,1,0]] 

In [157]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [158]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [162]:
np.sqrt(ar) # root of each elements

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [163]:
ar.sum()
           #ar = [[1,2,3],
           #      [4,5,6],
           #      [7,1,0]] 

np.int64(29)

In [164]:
ar.max()

np.int64(7)

In [165]:
ar.min()       #ar = [[1,2,3],
               #      [4,5,6],
               #      [7,1,0]] 

np.int64(0)

In [ ]:
np.where(ar>5) # Find a element

In [166]:
np.count_nonzero(ar) # Count nonzero Elements

8

In [167]:
import sys # Byite difference of python array & numpy array

In [168]:
py_ar = [0,4,55,2]

In [169]:
np_ar = np.array(py_ar)

In [170]:
sys.getsizeof(1) * len(py_ar)

112

In [171]:
np_ar.itemsize * np_ar.size

32